Feature/add supercluster visualization
forensic-architecture/timemap pull request #162
Opened 2020-10-06 17:22 UTC by ebefarooqui

This is a preliminary PR to get feedback for the supercluster visualization. Currently, the styles are still in question (opacity, size of cluster, cluster radius) and we will be reviewing different styles soon to gauge what is best for the user.

2020-10-09 11:37 UTC, breezykermo commented
Love this feature. Do you want general comments regarding what's missing and bugs, or just inline comments on the code reviewing what you've done so far?

2020-10-17 11:24 UTC, breezykermo requested changes
Really excellent work/feature! I've made a couple of structural suggestions around code quality. I haven't been able to test the feature yet in a browser, due to having the wrong config I think (have sent you a message privately).

2020-10-17 11:24 UTC, breezykermo commented on src/components/Map.jsx
> +        const validCoordinates = !!latitude && !!longitude
you could use `isLatitude` and `isLongitude` from common/utilities here to check more extensively and make it a bit more readable.

2020-10-17 11:24 UTC, breezykermo commented on src/components/Map.jsx
> +          acc.push(feature)
nice use of `reduce`!

2020-10-17 11:24 UTC, breezykermo commented on src/components/Map.jsx
> +    if (hash(nextProps.domain.locations) !== hash(this.props.domain.locations)) {
We could put this in a function in common/utilities now, e.g. `!isIdentical(nextProps.domain.locations, this.props.domain.locations)`, which just uses the hash under the hood. I've thought about this being an externality we could prune out at some point, so it might be sensible to add that layer of abstraction so it's easy to prune in the future.

2020-10-17 11:24 UTC, breezykermo commented on src/components/Map.jsx
> +      this.setState({ indexLoaded: true })
what appears on the map before the clusters are loaded? I see in `update` that `state.clusters` will remain an empty list. If it defaults to the old representation (events without clusters), would it perhaps be preferable to show a loading icon?

2020-10-17 11:24 UTC, breezykermo commented on src/components/presentational/Map/Clusters.jsx
> +    const styles = ({
no `()` needed

2020-10-17 11:24 UTC, breezykermo commented on src/components/presentational/Map/Clusters.jsx
> +    )
This `extraRender` logic is a good candidate for making into a HOC now, I think, given that it's used both here and in Events.jsx.

2020-10-19 16:36 UTC, ebefarooqui commented
This PR should be fully ready to review. I've attached the appropriate timemap config file [here](https://github.com/forensic-architecture/configs/blob/master/timemap/us_protests_cluster_config.js).

Note that the categories are currently broken on this branch, but you shouldn't need to test with them anyways. The styling for the clusters (opacity, size, cluster radius) are the ones decided on in the chat, but any and all suggestions welcome.

In order to run locally with updated data, I created a `test_export_events` tab in the datasheet, so in order to see the data locally, make sure that the return statement in `src/lib.js` in `ds-s` looks like the following:

`return {`
   `[`test_export_events`]: BP.deeprows,`
   `[`${prf('categories')}export_categories`]: [BP.groups, BP.rows],`
   `[`${prf('associations')}export_associations`]: BP.deeprows,`
   `[`${prf('sources')}export_sources`]: BP.deepids,`
   `[`${prf('sites')}export_sites`]: BP.rows`
  `}`

2020-10-19 19:00 UTC, ebefarooqui commented on src/common/utilities.js
> +  return Math.min(50, 10 + (pointCount / totalPoints) * 150)
They are essentially multiplication factors. Will leave a comment above

2020-10-19 19:07 UTC, ebefarooqui commented on src/components/Map.jsx
> +import DefsClusters from './presentational/Map/DefsClusters.jsx'
I was just testing out the radial gradients and so `Defs` is a remnant of that. I've left it for now, in case we ever specify in the config that we'd like radial gradients. Will also move it out into the `Clusters` component.

2020-10-19 19:07 UTC, ebefarooqui commented on src/components/Map.jsx
> +    this.index = null
gotcha

2020-10-19 19:10 UTC, ebefarooqui commented on src/components/Map.jsx
> +      this.loadClusterData(nextProps.domain.locations)
I do want to move a lot of the logic out, but it is tightly coupled with the Map component. I could scope it outside of the Map class, but then it would need access to instances of the map and index that are declared within that component. Will look into a better refactor soon, but tabling for now.

2020-10-19 19:14 UTC, ebefarooqui commented on src/components/Map.jsx
> +      this.setState({ indexLoaded: true })
Definitely, will need to add some sort of interim state so that the events are all loaded and then displayed.

2020-10-20 22:31 UTC, merged