Added generators for card layouts.
forensic-architecture/timemap pull request #182
Opened 2020-11-12 18:54 UTC by zacoppotamus

I figured adding a sibling generator file be the least invasive way. The generators are optionally defined in the timemap config, and have also been tested with the Yemen config (and the appropriate `datasheet-server` branch).  I'm using the optional chaining JS operator to ascertain the existence of the card layout setting in the redux-connected props — this feature is included in `@babel/plugin-preset-env@7.8.0`, which we have already. The linting fails because of this, but once we merge the `feature/build-system` branch, this won't be a problem as it uses [Prettier](https://prettier.io/) for linting.

2020-11-12 19:20 UTC, breezykermo commented
What's the plan to migrate this hardcoded `us2020` generator out of the codebase? Could it just go as a feature toggle in 'config.js' for the time being, instead of being inside the timemap source code?

2020-11-12 19:22 UTC, breezykermo requested changes
Is there any reason that we can't move the `us2020` generator into the us2020 config? I would rather keep aspects of particular instances from the timemap src code.

2020-11-12 19:26 UTC, breezykermo commented
I also think it would make more sense to move the `basic` generator inside the Redux store 'intial.js' default. It's currently inside the 'components' folder, however it's not a React component.

2020-11-16 16:13 UTC, zacoppotamus commented on src/components/CardStack.jsx
> +          content={this.props.cardUI.layout({
Here is the relevant change @breezykermo

2020-11-16 16:13 UTC, zacoppotamus commented on src/components/CardStack.jsx
> +          content={this.props.cardUI.layout({
Apologies for the crowded diff — it's due to having reverted to our current linting stack

2020-11-16 16:15 UTC, zacoppotamus commented
I believe this should address the requested changes @breezykermo. I moved the basic card layout inside the `common` folder, am calling it in `initial.js`, and am overriding changes through the config.

2020-11-18 06:16 UTC, breezykermo approved these changes

2020-11-18 06:16 UTC, breezykermo commented on src/common/card.js
> +}
nice! I like this cleanliness a lot more. So the current implementation requires a generator comparable to this one (specifying custom `value`s if they exist on the event object) to exist in the config?

2020-11-18 06:17 UTC, breezykermo commented on src/common/card.js
> +}
If so, could you make an equivalent PR to the configs repo?

2020-11-20 00:34 UTC, zacoppotamus commented on src/common/card.js
> +}
There's a pending PR with these changes in the configs repo :)

2020-11-20 06:35 UTC, merged